### PR TITLE
Adding Energy

### PR DESCRIPTION
**Pull request by vadkor**
Screenshot from 2022-11-29 12-59-10
Screenshot from 2022-11-29 12-57-54

### CODE REVIEW

**Comment by sumayahasancds** [comment]
Looks good to me!

**Review by JamesMBligh — COMMENTED** [review]
Rather than go through the code in detail (as there is a lot) I did a skim but I also pulled the branch and ran it.  Looks awesome.  Great work

Only comment I have is that there are a number of MaterialUI exception in the JS Console.  We should probably fix those before we ship

**Comment by vadkor** [comment]
Thanks, James! I've fixed a wrongly placed justifyContent attribute in one of MaterialUI _Grid_ s. Please check if it's fixed the exception.

**Review by CDR-API-Stream — APPROVED** [review]
Looks great :)

**Pull request merged**
