### PR TITLE
Update ING data source base URL

### LINKED ISSUE #226: Update ING endpoints in the Product Comparator
INGs public endpoints have changed  

Can these please be updated for the Product Comparator tool please?

Public Base URI:
https://id.ob.ing.com.au
Product endpoints:
https://id.ob.ing.com.au/cds-au/v1/banking/products
https://id.ob.ing.com.au/cds-au/v1/banking/products/{productId}](https://id.ob.ing.com.au/cds-au/v1/banking/products/{productId}

### PR DESCRIPTION
**Pull request by vadkor**
Resolves #226

### CODE REVIEW

**Review by sumayahasancds — APPROVED** [review]
Thanks Vadym, looks right!

**Comment by Susan-ING** [comment]
Hi,

This change doesnt seem to have taken effect in the Product Comparator tool yet? It is still displaying our old URL?

**Comment by vadkor** [comment]
Hi @Susan-ING
The Comparator has been redeployed. Try now. Don't forget to click the Synchronise button in the Data Sources section.

**Comment by Susan-ING** [comment]
Great I can see its updated now. Thanks

**Comment by Susan-ING** [comment]
Sorry just had a look through and its not returning Product Details - returning a 406? We are supporting both v3 and v4 of Product details and are not getting this response when accessing directly via postman.

**Comment by sumayahasancds** [comment]
Dear @Susan-ING<https://github.com/Susan-ING>,

Thank you for reaching out. Upon investigation, we found out that the comparator is returning 200 if the x-v is 4 and x-min-v is 1, 2 or 3.

We are not clear on what x-v values you used in your Postman requests. The Comparator uses x-v=3 by default, however if you change it to 4 you should not get any errors.

Kind Regards,
Sumaya Hasan
Engineering Lead | Data Standards Body
Consumer Data Right Division | Markets Group
Treasury
E ***@***.******@***.***>
W www.consumerdatastandards.gov.au<http://www.consumerdatastandards.gov.au/>

Consumer Data Standards acknowledges the Traditional Owners of the lands that we live and work on across Australia and pays its respect to Elders past and present.

PLEASE NOTE
The information contained in this email may be confidential or privileged. Any unauthorised use or disclosure is prohibited. If you have received this email in error, please delete it immediately and notify the sender by return email. Thank you. To the extent permitted by law, Consumer Data Standards does not represent, warrant and/or guarantee that the integrity of this communication has been maintained or that the communication is free of errors, virus, interception or interference.
Please consider the environment before printing this email.

[j+JkfqJLEUrNgAAAABJRU5ErkJggg==]<https://cdr-support.zendesk.com/>



From: Susan-ING ***@***.***>
Date: Monday, 13 March 2023 at 5:04 pm
To: ConsumerDataStandardsAustralia/product-comparator-demo ***@***.***>
Cc: Sumaya Hasan ***@***.***>, Review requested ***@***.***>
Subject: Re: [ConsumerDataStandardsAustralia/product-comparator-demo] Update ING data source base URL (PR #228)

Sorry just had a look through and its not returning Product Details - returning a 406? We are supporting both v3 and v4 of Product details and are not getting this response when accessing directly via postman.

**Pull request merged**
